CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_ID INTEGER PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCH_RESULT (
    MATCH_ID INTEGER PRIMARY KEY,
    GUEST_ID INTEGER NOT NULL,
    HOST_ID INTEGER NOT NULL,
    GUEST_GOALS INTEGER NOT NULL,
    HOST_GOALS INTEGER NOT NULL,
    MATCH_DATE DATE NOT NULL,
    FOREIGN KEY (GUEST_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (HOST_ID) REFERENCES TEAMS (TEAM_ID)
);

CREATE TABLE IF NOT EXISTS SEASON_LEAGUE (
    SEASON_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER NOT NULL,
    POINTS INTEGER DEFAULT 0,
    GOALS_SCORED INTEGER DEFAULT 0,
    GOALS_LOST INTEGER DEFAULT 0,
    GOALS_DIFFERENCE INTEGER DEFAULT 0,
    START_SEASON_YEAR INTEGER NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID)
);


