CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_ID INTEGER PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS SEASONS (
    SEASON_ID INTEGER PRIMARY KEY,
    START_SEASON_YEAR INTEGER NOT NULL,
    END_SEASON_YEAR INTEGER NOT NULL,
    SEASON_STATUS VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS SEASON_LEAGUE (
    SEASON_LEAGUE_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER NOT NULL,
    POINTS INTEGER DEFAULT 0,
    MATCHES INTEGER DEFAULT 0,
    MATCHES_WIN INTEGER DEFAULT 0,
    MATCHES_DRAW INTEGER DEFAULT 0,
    MATCHES_LOSS INTEGER DEFAULT 0,
    GOALS_SCORED INTEGER DEFAULT 0,
    GOALS_LOST INTEGER DEFAULT 0,
    GOALS_DIFFERENCE INTEGER DEFAULT 0,
    SEASON_ID INTEGER NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (SEASON_ID)
);

CREATE TABLE IF NOT EXISTS PARAMETERS (
    PARAMETER_ID INTEGER PRIMARY KEY,
    PARAMETER_NAME VARCHAR (100) NOT NULL,
    PARAMETER_VALUE VARCHAR (20) NOT NULL,
    PARAMETER_TYPE VARCHAR (10) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCHWEEKS (
    MATCHWEEK_ID INTEGER PRIMARY KEY,
    MATCHWEEK_NUMBER INTEGER NOT NULL,
    MATCHWEEK_STATUS VARCHAR (10) NOT NULL,
    SEASON_ID INTEGER NOT NULL,
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (SEASON_ID)
);

CREATE TABLE IF NOT EXISTS MATCH_RESULTS (
    MATCH_ID INTEGER PRIMARY KEY,
    MATCHWEEK_ID INTEGER NOT NULL,
    SEASON_ID INTEGER NOT NULL,
    GUEST_ID INTEGER NOT NULL,
    HOST_ID INTEGER NOT NULL,
    GUEST_GOALS INTEGER,
    HOST_GOALS INTEGER,
    MATCH_DATE TIMESTAMP NOT NULL,
    MATCH_STATUS VARCHAR (10) NOT NULL,
    FOREIGN KEY (GUEST_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (HOST_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (MATCHWEEK_ID) REFERENCES MATCHWEEKS (MATCHWEEK_ID),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (SEASON_ID),
    UNIQUE(SEASON_ID, HOST_ID, GUEST_ID)
);

INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('ALL_TEAMS_NUMBER', 'INTEGER', '18');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('CL_PROMOTED_TEAMS_NUMBER', 'INTEGER', '2');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('UCL_PROMOTED_TEAMS_NUMBER', 'INTEGER', '2');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('UECL_PROMOTED_TEAMS_NUMBER', 'INTEGER', '1');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('RELEGATED_TEAMS_NUMBER', 'INTEGER', '3');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('START_SEASON_DATE', 'DATE', '2025-08-15');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('END_SEASON_DATE', 'DATE', '2026-06-25');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('START_WINTER_BREAK', 'DATE', '2025-12-25');
INSERT INTO PARAMETERS (PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_VALUE) VALUES ('END_WINTER_BREAK', 'DATE', '2026-01-25');



