CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_ID INTEGER PRIMARY KEY,
    TEAM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCH_RESULT (
    MATCH_ID INTEGER PRIMARY KEY,
    GUEST_ID INTEGER NOT NULL,
    HOST_ID INTEGER NOT NULL,
    GUEST_GOALS INTEGER NOT NULL,
    HOST_GOALS INTEGER NOT NULL,
    MATCH_DATE DATE NOT NULL,
    FOREIGN KEY (GUEST_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (HOST_ID) REFERENCES TEAMS (TEAM_ID)
);

CREATE TABLE IF NOT EXISTS SEASON_LEAGUE (
    SEASON_LEAGUE_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER NOT NULL,
    POINTS INTEGER DEFAULT 0,
    MATCHES INTEGER DEFAULT 0,
    MATCHES_WIN INTEGER DEFAULT 0,
    MATCHES_DRAW INTEGER DEFAULT 0,
    MATCHES_LOSS INTEGER DEFAULT 0,
    GOALS_SCORED INTEGER DEFAULT 0,
    GOALS_LOST INTEGER DEFAULT 0,
    GOALS_DIFFERENCE INTEGER DEFAULT 0,
    SEASON_ID INTEGER NOT NULL,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (SEASON_ID)
);

CREATE TABLE IF NOT EXISTS SEASONS (
    SEASON_ID INTEGER PRIMARY KEY,
    START_SEASON_YEAR INTEGER NOT NULL,
    END_SEASON_YEAR INTEGER NOT NULL,
    SEASON_STATUS VARCHAR (15) NOT NULL
);


